# Generated by Django 5.2.4 on 2025-07-29 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_order_alter_contactus_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pincode',
            field=models.CharField(max_length=6),
        ),
    ]
