# Generated by Django 5.2.4 on 2025-07-29 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cart_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
